from setuptools import setup, find_packages

setup(
    name="hate_speech_detection",
    version="1.0.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "streamlit>=1.29.0",
        "fastapi>=0.104.1",
        "uvicorn>=0.24.0",
        "python-dotenv>=1.0.0",
        "pydantic>=2.4.2",
        "langchain==0.0.267",
        "langchain-community==0.0.6",
        "langchain-core==0.0.27",
        "langchain-experimental==0.0.20",
        "langchain-google-genai==0.0.3",
        "langgraph==0.0.20",
        "google-generativeai>=0.3.2",
        "faiss-cpu>=1.7.4",
        "sentence-transformers>=2.2.2",
        "openai-whisper>=20231117",
        "pandas>=2.1.3",
        "numpy>=1.26.2",
        "python-multipart>=0.0.6",
    ],
    description="Hate Speech Detection Assistant using GenAI, LangChain, and LangGraph",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/yourusername/hate_speech_detection",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.9",
)